print("Hello World")
print("Hello Neerajaa")
print("Hello Vanshhh")
print("Hello Samaksh")
print("Hello Vishal")
def fun(name):
  print('Hello {}'.format(name))
fun('World')
print("rohan")
print("bishal")
